language: generic
sudo: required
services:
- docker
cache:
  directories:
    - $GOPATH/pkg/dep
jobs:
  include:
    # Test
    - stage: test
      script: echo "test"
    # Deploy
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "deploy"
        on:
          repo: kubernetes-incubator/service-catalog
          all_branches: true
