language: generic
sudo: required
services:
- docker
cache:
  directories:
    - $GOPATH/pkg/dep
stages:
  - test
  - name: deploy
    if: type != pull_request
before_install:
  - |
      if [[ -z "$TRAVIS_COMMIT_RANGE" ]]; then
          # Builds triggered by initial commit of a new branch.
          DOCS_ONLY=0
      else
          DOCS_REGEX='(OWNERS|LICENSE)|(\.md$)|(^docs/)'
          [[ -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -vE $DOCS_REGEX)" ]]
          DOCS_ONLY=$?
      fi
jobs:
  include:
    # Test
    - script:
      - |
          if (( $DOCS_ONLY == 0 )); then
              echo "Running verify-docs"
              make verify-docs
          else
              echo "Running full build"
              make verify build build-integration build-e2e test images svcat
          fi
    # Deploy
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: script
        script: contrib/travis/deploy.sh
        on:
          repo: kubernetes-incubator/service-catalog
          all_branches: true
