language: generic
sudo: required
services:
- docker
cache:
  directories:
  - .glide
jobs:
  include:
    - stage: Verify and Build
      script: make verify build
    - stage: Test and Make Image
      script: make test images
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    repo: kubernetes-incubator/service-catalog
    all_branches: true
