apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  externalServiceClassName: user-provided-service
  externalServicePlanName: default
  parameters:
    credentials:
      name: root
      password: letmein
