apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  externalServiceClassName: user-provided-service
  externalServicePlanName: default-86064792-7ea2-467b-af93-ac9694d96d52
  parameters:
    credentials:
      name: root
      password: letmein
