---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podpreset-access
  namespace: default
rules:
  -
    apiGroups:
      - settings.servicecatalog.k8s.io
    resources:
      - podpresets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  -
    apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  -
    apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - update
  -
    apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podpreset-access-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podpreset-access
subjects:
  -
    kind: ServiceAccount
    name: default
    namespace: podpreset-crd-system
---
