apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-database
spec:
  selector:
    matchLabels:
      app: command
  env:
    - name: DB_HOST
      value: "localhost"
    - name: DB_PORT
      value: "6379"
