# Default values for Service Catalog
# determines whether the API server should be registered with the kube-aggregator
useAggregator: false
apiserver:
  # apiserver image to use
  image: quay.io/kubernetes-service-catalog/apiserver:v0.0.15
  # imagePullPolicy for the apiserver; valid values are "IfNotPresent",
  # "Never", and "Always"
  imagePullPolicy: Always
  aggregator:
    # priority is the priority of the APIService. Please see
    # https://github.com/kubernetes/kubernetes/blob/v1.7.0/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go#L56-L61
    # for more information on proper values of this field.
    #
    # This field is only applicable on clusters that expose APIService as a v1alpha1 field,
    # which is generally 1.6.x clusters
    priority: 100
    # groupPriorityMinimum is the minimum priority the group should have. Please see
    # https://github.com/kubernetes/kubernetes/blob/v1.7.0/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go#L56-L61
    # for more information on proper values of this field.
    groupPriorityMinimum: 10000
    # versionPriority is the ordering of this API inside of the group. Please see
    # https://github.com/kubernetes/kubernetes/blob/v1.7.0/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go#L56-L61
    # for more information on proper values of this field
    versionPriority: 20
  tls:
    # The name of the file that contains the certificate authority for the APIService object to 
    # register the Service Catalog API with the API aggregator in the APIRegistration object.
    # This field is required if apiserver.auth.enabled is true.
    caFileName:
    # The name of the file that contains the x509 certificate for use in the aforementioned
    # APIService object. This field is required if apiserver.auth.enabled is true.
    certFileName:
    # The name of the file that contains the private key for use in the aforementioned APIService
    # object. This field is required if apiserver.auth.enabled is true.
    # Base64-encoded private key
    keyFileName:
    # The name of the file that contains the CA to authenticate connections from API server
    # proxies. This field is not required. If it is not set, the service-catalog API server 
    # will be started with the --authentication-skip-lookup flag, which will disable the auth checks
    # from the API server proxies as well as client cert authentication.
    requestHeaderCA:
  # Attributes of the apiserver's service resource
  service:
    # Type of service; valid values are "LoadBalancer" and "NodePort"
    # NodePort is useful if deploying on bare metal or hacking locally on
    # minikube
    type: NodePort
    # Further configuration for services of type NodePort
    nodePort:
      # Available port in allowable range (e.g. 30000 - 32767 on minikube)
      # The TLS-enabled endpoint will be exposed here
      securePort: 30443
  storage:
    # The storage backend to use; valid values are "etcd" and "tpr"
    type: etcd
    # Further configuration for the etcd-based backend
    etcd:
      # Whether to embed an etcd container in the apiserver pod
      # THIS IS INADEQUATE FOR PRODUCTION USE!
      useEmbedded: true
      # etcd URL(s); override this if NOT using embedded etcd
      servers: http://localhost:2379
    tpr:
      # Some service catalog resources are not namespaced, but third party
      # resources must be; setting this designates a namespace that will be
      # treated as a container for such resources
      globalNamespace: servicecatalog
  # Log level; valid values are in the range 0 - 10
  verbosity: 10
  auth:
    # Enable or disable authentication and authorization.  Disabling authentication
    # and authorization can be useful for quickly getting the walkthrough up and running,
    # but is not suitable for production.
    enabled: false
  audit:
    # If true, enables the use of audit features via this chart.
    activated: false
    # If specified, audit log goes to specified path.
    logPath: "/tmp/service-catalog-apiserver-audit.log"
  serviceAccount: service-catalog-apiserver
controllerManager:
  # controller-manager image to use
  image: quay.io/kubernetes-service-catalog/controller-manager:v0.0.15
  # imagePullPolicy for the controller-manager; valid values are
  # "IfNotPresent", "Never", and "Always"
  imagePullPolicy: Always
  # Log level; valid values are in the range 0 - 10
  verbosity: 10
  # Resync interval; format is a duration (`20m`, `1h`, etc)
  resyncInterval: 5m
  # Broker relist interval; format is a duration (`20m`, `1h`, etc)
  brokerRelistInterval: 24h
  # Whether or not the controller supports a --broker-relist-interval flag. If this is 
  # set to true, brokerRelistInterval will be used as the value for that flag
  brokerRelistIntervalActivated: true
  # enables profiling via web interface host:port/debug/pprof/
  profiling:
    # Disable profiling via web interface host:port/debug/pprof/
    disabled: false
    # Enables lock contention profiling, if profiling is enabled.
    contentionProfiling: false
  leaderElection:
    # Whether the controller has option to set leader election namespace.
    activated: false
  serviceAccount: service-catalog-controller-manager
  # Controls whether the API server's TLS verification should be skipped.
  apiserverSkipVerify: true
