kind: Service
apiVersion: v1
metadata:
  name: user-bookstore-fe
spec:
  type: LoadBalancer
  selector:
    app: user-bookstore-fe
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-bookstore-fe
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-bookstore-fe
    spec:
      containers:
      - name: nodejs
        image: b.gcr.io/helm-sb-test/bookstore-nodejs:0.0.2
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstore-nodejs
              key: bookstore-database.hostname
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: bookstore-nodejs
              key: bookstore-database.port
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: bookstore-nodejs
              key: bookstore-database.username
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: bookstore-nodejs
              key: bookstore-database.password
        - name: MYSQL_DATABASE
          value: bookstore
