{{- if .Values.useAggregator }}
{{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1beta1" }}
apiVersion: apiregistration.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1alpha1" }}
apiVersion: apiregistration.k8s.io/v1alpha1
{{- end }}
kind: APIService
metadata:
  name: v1alpha1.servicecatalog.k8s.io
spec:
  group: servicecatalog.k8s.io
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "fullname" . }}-apiserver
  {{- if eq .Values.apiserver.tls.ca "" }}
  insecureSkipTLSVerify: true
  {{- else }}
  caBundle: {{ .Values.apiserver.tls.ca }}
  {{- end }}
  # Extension API Servers should have a priority value higher than the core API groups that have 100
  # The lower value here the higher priority
  priority: 150
{{ end }}
