apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-apiserver-cert
  labels:
    app: {{ template "fullname" . }}-apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ (.Files.Get .Values.apiserver.tls.certFileName) | b64enc }}
  tls.key: {{ (.Files.Get .Values.apiserver.tls.keyFileName) | b64enc }}
{{- if .Values.apiserver.tls.requestHeaderCA }}
  requestheader-ca.crt: {{ .Values.apiserver.tls.requestHeaderCA }}
{{- end }}
