apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.registry }}/controller:{{ if .Values.controllerVersion }}{{ .Values.controllerVersion }}{{ else }}{{ default "latest" .Values.version }}{{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
