apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: {{ if .Values.registry }}{{ .Values.registry }}/{{ end }}controller:{{ if .Values.controllerVersion }}{{ .Values.controllerVersion }}{{ else }}{{ default "latest" .Values.version }}{{ end }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10000
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
